### ISSUE TITLE
啊哦，你所访问的页面不存在了。

### ISSUE THREAD

**Issue by redflower2017** [ShawDa/unet-rgb#3]
Data's link is 404 error

**Comment by ShawDa** [comment]
The baidupan link is available for me.
I make a new link:
链接：https://pan.baidu.com/s/17VknCRSIscrr5hQtxhb0KA 
提取码：zcxf

**Comment by redflower2017** [comment]
> The baidupan link is available for me.
> I make a new link:
> 链接：https://pan.baidu.com/s/17VknCRSIscrr5hQtxhb0KA
> 提取码：zcxf

this have same error as
啊哦，你所访问的页面不存在了。
可能的原因：

1.在地址栏中输入了错误的地址。

2.你点击的某个链接已过期。

返回上一级页面>

回到网站首页>

**Comment by ShawDa** [comment]
The original dataset is here:https://www.kaggle.com/c/carvana-image-masking-challenge/data. I choose partial data for train and test.
