### ISSUE TITLE
Implementation for satellite imagery?

### ISSUE THREAD

**Issue by kegro** [ShawDa/unet-rgb#4]
This is not really an issue, but more of a request :) You write you made an implementation of unet-rgb for satellite imagery. Is this a repository you'd consider sharing?

**Comment by ShawDa** [comment]
It's used for Remote Sensing Image exactly. And U can make an implementation on your own dataset.

**Comment by kegro** [comment]
Aha, sorry I should have looked more carefully. I thought you used the repo for the vidcam only, and the satellite implementation was slightly different. Great, thanks!
