### ISSUE TITLE
training and testing on rectangular images

### ISSUE THREAD

**Issue by Mahi-Mai** [ShawDa/unet-rgb#7]
Hello ShawDa,

Thanks for sharing your code!  I've been playing around with UNet in Python.  I've been wondering how you manage to train and test on images that aren't perfect squares?  If I send in a not-square input image, I'll get a squashed square output.  Of course, resizing it doesn't help much...

Any insight you have to share is appreciated.  Thanks!

**Comment by ShawDa** [comment]
The model's input and output are squares. So we can change rectangular to square before input and change square to rectangular after output to get what we want. The process methods are within codes.
