### ISSUE TITLE
Making pre processing ?

### ISSUE THREAD

**Issue by furkan59** [ShawDa/unet-rgb#9]
Hi,

Great post and nicely coded. Your coding is very clear. 

If we apply pre processing like k-means before semantic segmentation would it help to segment better ?

**Comment by ShawDa** [comment]
Do u mean that use k-means to make similar pixels together first？
I dont think that can help a lot since k-means may lost some features of pixel.

**Comment by furkan59** [comment]
Thanks it tried it. It does not work well. Making k means does not help.
